### ISSUE TITLE
Fix TransactionBuilder instantiation in `index.ts`

### ISSUE THREAD

**Issue by marktoda** [BitGo/bitgo-account-lib#28]
# Overview

In index.ts, we see this instantiation:
```
  if (supportedCoins.includes(coin)) {
    return new Trx.TransactionBuilder(coins.get(coin));
  }
```
It is supposed to be able to instantiate a TransactionBuilder for whatever coin it is given, but it specifically always uses the `Trx` coin-specific transaction builder. 

Refactor this function so that it actually instantiates the transaction builder based on the coin it is passed

# Definition of Done
- Tests should still pass without change
- This function shouldn't use any `Trx`-specific code
- If we were to add another coin TransactionBuilder, and give this function the name of that coin, it should correctly instantiate it.

**Comment by argjv** [comment]
I'm fixing this for Tezos
